service: DonationTrackerCrawler

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:event-uuid}
  environment:
    TRACKER_URL: ${opt:tracker-url}
    TRACKER_EVENT_ID: ${opt:tracker-event-id}
    SERVER_URL: ${opt:server-url}
    EVENT_UUID: ${opt:event-uuid}
  region: ap-southeast-1

functions:
  runs:
    handler: handler.runs
    events:
      - schedule: cron(0,12,24,36,48 * * ? *)
  runners:
    handler: handler.runners
    events:
      - schedule: cron(6,18,30,42,54 * * ? *)
