service: DonationTrackerCrawler

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:ap-southeast-1:*:*"


functions:
  run:
    handler: main.run
    events:
      - schedule: cron(0/6 * * * ? *)
