service: DonationTrackerCrawler

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1
	environment:
		TABLE_NAME: 'schedule-change'
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:ap-southeast-1:*:*"

functions:
  sgdq2018:
    handler: main.sgdq2018.run
    events:
      - schedule: cron(0/6 * * * ? *)
