service: DonationTrackerCrawler

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:event-uuid}
  environment:
    RUN_URL: ${opt:run-url}
    RUNNER_URL: ${opt:runner-url}
    SERVER_URL: ${opt:server-url}
    EVENT_UUID: ${opt:event-uuid}
  region: ap-southeast-1

functions:
  main:
    handler: handler.main
    events:
      - schedule: rate(6 minutes)
