service: schedule-change

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage}
  region: ap-southeast-1
  environment:
    TABLE_NAME: schedule-change-${opt:stage}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:ap-southeast-1:*:*"

functions:
  sgdq2018:
    handler: build/sgdq2018.default
    events:
      - schedule: cron(0/6 * * * ? *)

resources:
  Resources:
    scheduleChangeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: schedule-change-${opt:stage}
        AttributeDefinitions:
          - AttributeName: eventName
            AttributeType: S
        KeySchema:
          - AttributeName: eventName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
